/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginVisao.java
 *
 * Created on 16/03/2010, 17:41:27
 */

package sgps.visao;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import sgps.classeMapeada.Usuario;
import sgps.controle.*;



/**
 *
 * @author martins
 */
public class LoginVisao extends javax.swing.JInternalFrame {

    /** Creates new form LoginVisao */
    public LoginVisao(MenuPrincipalVisao principal) {
        this.principal = principal;
        initComponents();
        this.requestFocus();
        this.transferFocusUpCycle();
        this.toFront();
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpDados = new javax.swing.JPanel();
        jlLogin = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbOk = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        tfSenha = new javax.swing.JPasswordField();

        setBackground(java.awt.Color.lightGray);
        setClosable(true);
        setIconifiable(true);
        setTitle("Identicação do Usuário");
        setVisible(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpFundo.setBackground(java.awt.Color.lightGray);
        jpFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgps/imagens/Logo_login.png"))); // NOI18N
        jpFundo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jpDados.setBackground(new java.awt.Color(204, 204, 204));
        jpDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        jlLogin.setFont(new java.awt.Font("Tahoma", 1, 14));
        jlLogin.setText("Login:");

        tfLogin.setText("usuario");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Senha:");

        jbOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgps/imagens/Acesso16.PNG"))); // NOI18N
        jbOk.setText("ok");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgps/imagens/Cancelar.png"))); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        tfSenha.setText("jPddddd");

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlLogin)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(tfLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jbOk)
                        .addGap(18, 18, 18)
                        .addComponent(jbSair)))
                .addContainerGap())
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLogin)
                    .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOk)
                    .addComponent(jbSair))
                .addContainerGap())
        );

        jpFundo.add(jpDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        getContentPane().add(jpFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
     UsuarioControle usuarioControle = new UsuarioControle();
     Usuario us = usuarioControle.getInstanciaUsuario();
     EntityManager em= usuarioControle.getEntityManager();
     Query query;
     query = em.createNamedQuery("Usuario.verificaLogin");
     query.setParameter("nomeusuario", tfLogin.getText());
     query.setParameter("senhausuario", tfSenha.getText());
      List<Usuario> lus = new ArrayList<Usuario>();
      lus = query.getResultList();
      if (lus.size() > 0) {
          JOptionPane.showMessageDialog(null, "usuario existente");
           // String args[] = new String[1];
            //args[0] = lus.get(0).ge.toString();
           //Menu.main(args);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário/Senha incorretos");
            dispose();
        }
        /*
    * query = entityManager.createNamedQuery("Funcionario.verificaLogin");
        query.setParameter("loginFuncionario", jTextField1.getText());
        query.setParameter("senhaFuncionario", EncriptaSenha.encripta(jPasswordField1.getText()));
        List<Funcionario> data = query.getResultList();

        if (data.size() > 0) {
            String args[] = new String[1];
            args[0] = data.get(0).getCodFuncionario().toString();
            Menu.main(args);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário/Senha incorretos");
            dispose();
        }

}
    *
*/


    }//GEN-LAST:event_jbOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbOk;
    private javax.swing.JButton jbSair;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JPanel jpDados;
    private javax.swing.JPanel jpFundo;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
    MenuPrincipalVisao principal;
}
