/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginVisao.java
 *
 * Created on 16/03/2010, 17:41:27
 */
package sgps.visao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import sgps.classeMapeada.Acessousuario;
import sgps.classeMapeada.Telasistema;
import sgps.controle.*;

/**
 *
 * @author martins
 */
public class LoginVisao extends javax.swing.JInternalFrame {

    /** Creates new form LoginVisao */
    public LoginVisao(MenuPrincipalVisao principal) {
        this.principal = principal;
        initComponents();
        this.requestFocus();
        this.transferFocusUpCycle();
        this.toFront();
    }

    public LoginVisao() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpDados = new javax.swing.JPanel();
        jlLogin = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbOk = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        tfSenha = new javax.swing.JPasswordField();

        setBackground(java.awt.Color.lightGray);
        setClosable(true);
        setIconifiable(true);
        setTitle("Identicação do Usuário");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpFundo.setBackground(java.awt.Color.lightGray);
        jpFundo.setPreferredSize(new java.awt.Dimension(262, 368));
        jpFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgps/imagens/Logo_login.png"))); // NOI18N
        jpFundo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 180, 130));

        jpDados.setBackground(new java.awt.Color(204, 204, 204));
        jpDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));
        jpDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlLogin.setFont(new java.awt.Font("Tahoma", 1, 14));
        jlLogin.setText("Login:");
        jpDados.add(jlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        tfLogin.setFont(new java.awt.Font("Tahoma", 0, 14));
        jpDados.add(tfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Senha:");
        jpDados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jbOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgps/imagens/Acesso16.PNG"))); // NOI18N
        jbOk.setText("ok");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });
        jpDados.add(jbOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgps/imagens/Cancelar.png"))); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });
        jpDados.add(jbSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));
        jpDados.add(tfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, -1));

        jpFundo.add(jpDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 140, 190, 170));

        getContentPane().add(jpFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 262, 329));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        System.exit(0);
}//GEN-LAST:event_jbSairActionPerformed

    public List<String> retornaUsuarioSenha() {
        List<String> usuarioSenhaList = new ArrayList<String>();
        usuarioSenhaList.add(tfLogin.getText());
        usuarioSenhaList.add(tfLogin.getText());
        return usuarioSenhaList;
    }

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        AcessoControle acessoControle = new AcessoControle();
        List<Acessousuario> listaAcesso = new ArrayList<Acessousuario>();
        Telasistema tela = new Telasistema();
        if (acessoControle.verificaLogin(tfLogin.getText(), tfSenha.getText())) {
            JOptionPane.showMessageDialog(null, "usuario habilitado");
            LoginVisao loginVisao = new LoginVisao();
            listaAcesso = acessoControle.listaDeAcesso(tfLogin.getText(), tfSenha.getText());
            for (Acessousuario acesso : listaAcesso) {
                tela = acesso.getTelasistema();
                switch (tela.getIdtelasistema()) {
                    case 1:
                        principal.miCadAnimal.setEnabled(acesso.getFlagtipoacesso());
                    case 2:
                        principal.miCadUsuario.setEnabled(acesso.getFlagtipoacesso());
                    case 3:
                        principal.jmConfroleAcessoUsuario.setEnabled(acesso.getFlagtipoacesso());
                        break;
                }
            }

            dispose();

        } else {
            JOptionPane.showMessageDialog(null, "usuário ou senha incorreto");

        }



    }//GEN-LAST:event_jbOkActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbOk;
    private javax.swing.JButton jbSair;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JPanel jpDados;
    private javax.swing.JPanel jpFundo;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
    MenuPrincipalVisao principal;
}
