/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formularioPadrao.java
 *
 * Created on 11/02/2010, 14:06:48
 */

package formulariopadrao;

/**
 *
 * @author martins
 */
public class formularioPadrao extends javax.swing.JFrame {

    /** Creates new form formularioPadrao */
    public formularioPadrao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jL_codigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        tf_codigo = new javax.swing.JTextField();
        jl_cpf = new javax.swing.JLabel();
        jl_rg = new javax.swing.JLabel();
        tf_cpf = new javax.swing.JTextField();
        jl_dataNascimento = new javax.swing.JLabel();
        tf_rg = new javax.swing.JTextField();
        tf_dataNascimento = new javax.swing.JTextField();
        tf_foneRes = new javax.swing.JTextField();
        jl_foneRes = new javax.swing.JLabel();
        tf_FoneCel = new javax.swing.JTextField();
        jl_FoneCel = new javax.swing.JLabel();
        jl_FoneCom = new javax.swing.JLabel();
        tf_FoneCom = new javax.swing.JTextField();
        tf_dataCadastro = new javax.swing.JTextField();
        jL_dataCadastro = new javax.swing.JLabel();
        jL_email = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        jL_observacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jl_foneRes1 = new javax.swing.JLabel();
        tf_foneRes1 = new javax.swing.JTextField();
        jl_foneRes2 = new javax.swing.JLabel();
        tf_foneRes2 = new javax.swing.JTextField();
        jl_foneRes3 = new javax.swing.JLabel();
        tf_foneRes3 = new javax.swing.JTextField();
        jl_foneRes4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jl_foneRes5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        jPanel2.setBackground(new java.awt.Color(217, 242, 246));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 500));

        jL_codigo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jL_codigo.setText("Codigo.:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Nome.:");

        tf_nome.setToolTipText("digite o nome da cidade");
        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });

        tf_codigo.setToolTipText("digite  o codigo da cidade");
        tf_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoActionPerformed(evt);
            }
        });

        jl_cpf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_cpf.setText("CPF.:");

        jl_rg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_rg.setText("RG.:");

        tf_cpf.setToolTipText("digite o nome da cidade");
        tf_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cpfActionPerformed(evt);
            }
        });

        jl_dataNascimento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_dataNascimento.setText("Data Nasc.:");

        tf_rg.setToolTipText("digite o nome da cidade");
        tf_rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rgActionPerformed(evt);
            }
        });

        tf_dataNascimento.setToolTipText("digite o nome da cidade");
        tf_dataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dataNascimentoActionPerformed(evt);
            }
        });

        tf_foneRes.setToolTipText("digite o nome da cidade");
        tf_foneRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_foneResActionPerformed(evt);
            }
        });

        jl_foneRes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_foneRes.setText("Fone Res.:");

        tf_FoneCel.setToolTipText("digite o nome da cidade");
        tf_FoneCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_FoneCelActionPerformed(evt);
            }
        });

        jl_FoneCel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_FoneCel.setText("Fone Cel.:");

        jl_FoneCom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_FoneCom.setText("Fone Com.:");

        tf_FoneCom.setToolTipText("digite o nome da cidade");
        tf_FoneCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_FoneComActionPerformed(evt);
            }
        });

        tf_dataCadastro.setToolTipText("digite o nome da cidade");
        tf_dataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dataCadastroActionPerformed(evt);
            }
        });

        jL_dataCadastro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jL_dataCadastro.setText("Data Cadastro.:");

        jL_email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jL_email.setText("E-mail.:");

        tf_email.setToolTipText("digite  o codigo da cidade");
        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });

        jL_observacao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jL_observacao.setText("Observacao.:");

        jScrollPane1.setViewportView(jTextPane1);

        jl_foneRes1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_foneRes1.setText("Rua:");

        tf_foneRes1.setToolTipText("digite o nome da cidade");
        tf_foneRes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_foneRes1ActionPerformed(evt);
            }
        });

        jl_foneRes2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_foneRes2.setText("CEP");

        tf_foneRes2.setToolTipText("digite o nome da cidade");
        tf_foneRes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_foneRes2ActionPerformed(evt);
            }
        });

        jl_foneRes3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_foneRes3.setText("N.:");

        tf_foneRes3.setToolTipText("digite o nome da cidade");
        tf_foneRes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_foneRes3ActionPerformed(evt);
            }
        });

        jl_foneRes4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_foneRes4.setText("Cidade");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jl_foneRes5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_foneRes5.setText("UF");

        jButton1.setText("SALVAR");

        jButton2.setText("VOLTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jL_codigo)
                                .addGap(10, 10, 10)
                                .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                .addGap(117, 117, 117))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jl_dataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jL_dataCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_dataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jl_foneRes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_foneRes, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jl_FoneCom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_FoneCom, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jl_FoneCel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_FoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jL_observacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jl_rg)
                                .addGap(14, 14, 14)
                                .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jl_cpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jL_email)
                                .addGap(18, 18, 18)
                                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_foneRes1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_foneRes1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jl_foneRes2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_foneRes2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jl_foneRes3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_foneRes3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jl_foneRes4)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jl_foneRes5)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jButton2)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_codigo)
                    .addComponent(jLabel4)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_rg)
                    .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_cpf)
                    .addComponent(jL_email)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_dataNascimento)
                    .addComponent(tf_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_dataCadastro)
                    .addComponent(tf_dataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_FoneCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_FoneCom)
                    .addComponent(jl_FoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_FoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_foneRes)
                    .addComponent(tf_foneRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jL_observacao))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_foneRes1)
                    .addComponent(tf_foneRes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_foneRes2)
                    .addComponent(tf_foneRes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_foneRes3)
                    .addComponent(tf_foneRes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_foneRes4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_foneRes5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_emailActionPerformed

    private void tf_dataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dataCadastroActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_dataCadastroActionPerformed

    private void tf_FoneComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_FoneComActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_FoneComActionPerformed

    private void tf_FoneCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_FoneCelActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_FoneCelActionPerformed

    private void tf_foneResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_foneResActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_foneResActionPerformed

    private void tf_dataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dataNascimentoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_dataNascimentoActionPerformed

    private void tf_rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rgActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_rgActionPerformed

    private void tf_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cpfActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_cpfActionPerformed

    private void tf_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_codigoActionPerformed

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_nomeActionPerformed

    private void tf_foneRes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_foneRes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_foneRes1ActionPerformed

    private void tf_foneRes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_foneRes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_foneRes2ActionPerformed

    private void tf_foneRes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_foneRes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_foneRes3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jL_codigo;
    private javax.swing.JLabel jL_dataCadastro;
    private javax.swing.JLabel jL_email;
    private javax.swing.JLabel jL_observacao;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel jl_FoneCel;
    private javax.swing.JLabel jl_FoneCom;
    private javax.swing.JLabel jl_cpf;
    private javax.swing.JLabel jl_dataNascimento;
    private javax.swing.JLabel jl_foneRes;
    private javax.swing.JLabel jl_foneRes1;
    private javax.swing.JLabel jl_foneRes2;
    private javax.swing.JLabel jl_foneRes3;
    private javax.swing.JLabel jl_foneRes4;
    private javax.swing.JLabel jl_foneRes5;
    private javax.swing.JLabel jl_rg;
    private javax.swing.JTextField tf_FoneCel;
    private javax.swing.JTextField tf_FoneCom;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_cpf;
    private javax.swing.JTextField tf_dataCadastro;
    private javax.swing.JTextField tf_dataNascimento;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_foneRes;
    private javax.swing.JTextField tf_foneRes1;
    private javax.swing.JTextField tf_foneRes2;
    private javax.swing.JTextField tf_foneRes3;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_rg;
    // End of variables declaration//GEN-END:variables

    private void ordem_visualizacao(String string) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

}
