/*
 * MenuEstoque.java
 *
 * Created on 7 de Abril de 2009, 09:59
 */

/**
 *
 * @author  martins
 */

import cadastro.cad_cidade;
import utilitarios.data;
public class MenuEstoque extends javax.swing.JFrame {
data mostra_data = new data();
    /** Creates new form MenuEstoque */
    public MenuEstoque()
    {
        initComponents();   
        
        mostra_data.le_data();
        label_data.setText("Data: "+mostra_data.dia_semana+" , "+mostra_data.dia+" de "+mostra_data.mes+" de "+mostra_data.ano);
        timer1.start();
       }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        clente = new javax.swing.JButton();
        cidade = new javax.swing.JButton();
        bairro = new javax.swing.JButton();
        sairIcone = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_data = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_hora = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenuItem();
        Funcionário = new javax.swing.JMenuItem();
        Cargo = new javax.swing.JMenuItem();
        Cidade = new javax.swing.JMenuItem();
        Bairro = new javax.swing.JMenuItem();
        Fornecedores = new javax.swing.JMenuItem();
        Estoque = new javax.swing.JMenu();
        Implantação = new javax.swing.JMenuItem();
        Entrada = new javax.swing.JMenuItem();
        Saída = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        sair = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        Consulta = new javax.swing.JMenu();
        Relatório = new javax.swing.JMenu();
        Utilitário = new javax.swing.JMenu();
        Sair = new javax.swing.JMenu();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA PARA GEST\u00c3O DE ESTOQUE");
        setAlwaysOnTop(true);
        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        clente.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\Martins\\Meus documentos\\programacao\\java\\Estoque\\imagens\\Icones\\icones\\PNG\\Apps\\146(cliente).png"));
        clente.setText("CLIENTE");

        cidade.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\Martins\\Meus documentos\\programacao\\java\\Estoque\\imagens\\Icones\\icones\\PNG\\Apps\\123(cidade).png"));
        cidade.setText("Cidade");
        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });

        bairro.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\Martins\\Meus documentos\\programacao\\java\\Estoque\\imagens\\Icones\\icones\\PNG\\Apps\\124(bairro).png"));
        bairro.setText("BAIRRO");

        sairIcone.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\Martins\\Meus documentos\\programacao\\java\\Estoque\\imagens\\Icones\\icones\\PNG\\Actions\\133(sair).png"));
        sairIcone.setText("sair");
        sairIcone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairIconeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(sairIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sairIcone, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addComponent(cidade, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addComponent(clente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(bairro, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        label_data.setFont(new java.awt.Font("Tahoma", 1, 14));
        label_data.setText("Data.:");

        label_hora.setText("Hora:");

        jLabel4.setText("jLabel4");
        jLabel4.setBounds(0, 0, -1, -1);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setIcon(new javax.swing.ImageIcon("Z:\\Meus documentos\\programacao\\Estoque\\imagens\\papel de parede.jpeg"));

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 255), null, null));
        Cadastro.setText("Cliente");
        Cliente.setText("Cliente");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });

        Cadastro.add(Cliente);

        Funcionário.setText("Funcion\u00e1rio");
        Cadastro.add(Funcionário);

        Cargo.setText("Cargo");
        Cadastro.add(Cargo);

        Cidade.setText("Cidade");
        Cadastro.add(Cidade);

        Bairro.setText("Bairro");
        Cadastro.add(Bairro);

        Fornecedores.setText("Fornecedores");
        Cadastro.add(Fornecedores);

        Estoque.setText("Estoque");
        Implantação.setText("Implanta\u00e7\u00e3o");
        Estoque.add(Implantação);

        Entrada.setText("Entrada");
        Estoque.add(Entrada);

        Saída.setText("Sa\u00edda");
        Estoque.add(Saída);

        Cadastro.add(Estoque);

        Cadastro.add(jSeparator1);

        sair.setText("Sair");
        Cadastro.add(sair);

        Cadastro.add(jSeparator2);

        jMenuBar1.add(Cadastro);

        Consulta.setText("Consulta");
        jMenuBar1.add(Consulta);

        Relatório.setLabel("Relatorio");
        jMenuBar1.add(Relatório);

        Utilitário.setLabel("Utilitarios");
        jMenuBar1.add(Utilitário);

        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        jMenuBar1.add(Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(jLabel3)
                .addContainerGap(420, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)))
                .addGap(478, 478, 478)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1151, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(139, 139, 139))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1796, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_data, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2266, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2489, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel5))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_hora)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(268, 268, 268))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addContainerGap())))
        );
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-786)/2, (screenSize.height-458)/2, 786, 458);
    }// </editor-fold>//GEN-END:initComponents

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
// TODO add your handling code here:
        mostra_data.le_hora();
        label_hora.setText("Hora: "+mostra_data.hora);
    }//GEN-LAST:event_timer1OnTime

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_ClienteActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
      System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_SairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_SairMouseClicked

    private void sairIconeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairIconeActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_sairIconeActionPerformed

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
         new cad_cidade().show();       // TODO add your handling code here:
    }//GEN-LAST:event_cidadeActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEstoque().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Bairro;
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem Cargo;
    private javax.swing.JMenuItem Cidade;
    private javax.swing.JMenuItem Cliente;
    private javax.swing.JMenu Consulta;
    private javax.swing.JMenuItem Entrada;
    private javax.swing.JMenu Estoque;
    private javax.swing.JMenuItem Fornecedores;
    private javax.swing.JMenuItem Funcionário;
    private javax.swing.JMenuItem Implantação;
    private javax.swing.JMenu Relatório;
    private javax.swing.JMenu Sair;
    private javax.swing.JMenuItem Saída;
    private javax.swing.JMenu Utilitário;
    private javax.swing.JButton bairro;
    private javax.swing.JButton cidade;
    private javax.swing.JButton clente;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_data;
    private javax.swing.JLabel label_hora;
    private javax.swing.JMenuItem sair;
    private javax.swing.JButton sairIcone;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
    
}
