/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formularioPadrao.java
 *
 * Created on 11/02/2010, 14:06:48
 */

package formulariopadrao;

/**
 *
 * @author martins
 */
public class formularioManutencaoPadrao extends javax.swing.JFrame {

    /** Creates new form formularioPadrao */
    public formularioManutencaoPadrao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioButtonCodigo = new javax.swing.JRadioButton();
        radioButtonNome = new javax.swing.JRadioButton();
        radioButtonNome1 = new javax.swing.JRadioButton();
        radioButtonNome2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_cliente = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tf_pesquisa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        setBackground(new java.awt.Color(51, 102, 255));

        jPanel2.setBackground(new java.awt.Color(217, 242, 246));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ordenar por:");

        radioButtonCodigo.setBackground(new java.awt.Color(217, 242, 246));
        radioButtonCodigo.setText("Codigo");
        radioButtonCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCodigoActionPerformed(evt);
            }
        });

        radioButtonNome.setBackground(new java.awt.Color(217, 242, 246));
        radioButtonNome.setSelected(true);
        radioButtonNome.setText("Nome");
        radioButtonNome.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonNomeActionPerformed(evt);
            }
        });

        radioButtonNome1.setBackground(new java.awt.Color(217, 242, 246));
        radioButtonNome1.setSelected(true);
        radioButtonNome1.setText(" email");
        radioButtonNome1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonNome1ActionPerformed(evt);
            }
        });

        radioButtonNome2.setBackground(new java.awt.Color(217, 242, 246));
        radioButtonNome2.setSelected(true);
        radioButtonNome2.setText("Cidade/UF");
        radioButtonNome2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonNome2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(radioButtonCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(radioButtonNome)
                        .addGap(18, 18, 18)
                        .addComponent(radioButtonNome1)
                        .addGap(18, 18, 18)
                        .addComponent(radioButtonNome2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonCodigo)
                    .addComponent(radioButtonNome2)
                    .addComponent(radioButtonNome1)
                    .addComponent(radioButtonNome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtb_cliente.setAutoCreateRowSorter(true);
        jtb_cliente.setBackground(new java.awt.Color(217, 242, 246));
        jtb_cliente.setBorder(new javax.swing.border.MatteBorder(null));
        jtb_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtb_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Fone Res.", "Fone Com.", "Fone Cel.", "E-mail"
            }
        ));
        jtb_cliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jtb_cliente.setCellSelectionEnabled(true);
        jtb_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtb_cliente.setDropMode(javax.swing.DropMode.INSERT);
        jtb_cliente.setGridColor(new java.awt.Color(0, 0, 0));
        jtb_cliente.setName(""); // NOI18N
        jScrollPane2.setViewportView(jtb_cliente);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tf_pesquisa.setToolTipText("digite o nome da cidade para pesquisar");
        tf_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pesquisaActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa.jpg"))); // NOI18N

        jButton1.setText("Pesquisa Avançada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar");

        jButton3.setText("Alterar");

        jButton4.setText("Excluir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(57, 57, 57)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(245, 245, 245))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)))
                            .addComponent(jLabel3)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonNomeActionPerformed
        ordem_visualizacao("nome");
}//GEN-LAST:event_radioButtonNomeActionPerformed

    private void radioButtonCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCodigoActionPerformed
        ordem_visualizacao("codigo");
}//GEN-LAST:event_radioButtonCodigoActionPerformed

    private void tf_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pesquisaActionPerformed
        try {

            con_cliente.resultset.first();
            String igual = "n";
            int tamanho_pesquisa = tf_pesquisa.getText().length();
            while(igual == "n") {
                String pesquisado = con_cliente.resultset.getString("nome").substring(0, (tamanho_pesquisa));

                if (pesquisado.equals(tf_pesquisa.getText())) {
                    igual = "s";
                } else
                    con_cliente.resultset.next();
            }
            tf_codigo.setText(con_cliente.resultset.getString("codigo"));
            mostraDados();
            jcb_pesquisar.setSelectedItem(tf_nome.getText());
            con_cliente.executaSQL("select * from cliente where nome like '"+tf_pesquisa.getText()+"%' order by "+ordenacao);
            preencher_jtable();
        }

        catch(SQLException erro) {

            JOptionPane.showMessageDialog(null,"Erro ao tentar pesquisar via digita?AO!"+erro);
        }
}//GEN-LAST:event_tf_pesquisaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radioButtonNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonNome1ActionPerformed

    private void radioButtonNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonNome2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioManutencaoPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtb_cliente;
    private javax.swing.JRadioButton radioButtonCodigo;
    private javax.swing.JRadioButton radioButtonNome;
    private javax.swing.JRadioButton radioButtonNome1;
    private javax.swing.JRadioButton radioButtonNome2;
    private javax.swing.JTextField tf_pesquisa;
    // End of variables declaration//GEN-END:variables

    private void ordem_visualizacao(String string) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

}
