package cadastro;
import utilitarios.conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


    public class cliente extends javax.swing.JFrame {
    conexao con_cliente;
    int navega = 0;
    int pesquisa_combo = 0;
    String ordenacao = "nome";
        public cliente() {
        initComponents();
        con_cliente= new conexao();
        con_cliente.conecta();

        con_cliente.executaSQL("select * from cliente order by "+ordenacao);
        
        try
     {
         while (con_cliente.resultset.next())
             jcb_pesquisar.addItem(con_cliente.resultset.getString("nome"));
         
          con_cliente.resultset.first();
           mostraDados();
          
      }
          
        catch(SQLException erro)
        {

            JOptionPane.showMessageDialog(null,"Erro ao tenta visualizar o registro!"+erro);
        }
        preencher_jtable(); //preenche o jtable
       
    }
         
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOrdenacao = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jL_codigo = new javax.swing.JLabel();
        cb_endereco = new javax.swing.JComboBox();
        tf_codigo = new javax.swing.JTextField();
        tf_nome = new javax.swing.JTextField();
        botao_primeiro_registro = new javax.swing.JButton();
        botao_registro_anterior = new javax.swing.JButton();
        botao_registro_frente = new javax.swing.JButton();
        botao_ultimo_registro = new javax.swing.JButton();
        botao_gravar = new javax.swing.JButton();
        botao_incluir = new javax.swing.JButton();
        botao_excluir = new javax.swing.JButton();
        botao_alterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tf_pesquisa = new javax.swing.JTextField();
        jcb_pesquisar = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_cliente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioButtonCodigo = new javax.swing.JRadioButton();
        radioButtonNome = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jl_titulo_cliente = new javax.swing.JLabel();
        jl_endereco = new javax.swing.JLabel();
        tf_CodLog = new javax.swing.JTextField();
        tf_numero = new javax.swing.JTextField();
        jl_numero = new javax.swing.JLabel();
        jl_complemento = new javax.swing.JLabel();
        tf_complemento = new javax.swing.JTextField();
        jl_bairro = new javax.swing.JLabel();
        tf_bairro = new javax.swing.JTextField();
        cb_bairro = new javax.swing.JComboBox();
        jl_cidade = new javax.swing.JLabel();
        tf_cidade = new javax.swing.JTextField();
        cb_cidade = new javax.swing.JComboBox();
        jl_cpf = new javax.swing.JLabel();
        tf_cpf = new javax.swing.JTextField();
        jl_cep = new javax.swing.JLabel();
        tf_cep = new javax.swing.JTextField();
        jl_rg = new javax.swing.JLabel();
        tf_rg = new javax.swing.JTextField();
        tf_FoneCel = new javax.swing.JTextField();
        jl_FoneCel = new javax.swing.JLabel();
        tf_dataNascimento = new javax.swing.JTextField();
        jl_dataNascimento = new javax.swing.JLabel();
        tf_foneRes = new javax.swing.JTextField();
        jl_foneRes = new javax.swing.JLabel();
        jl_FoneCom = new javax.swing.JLabel();
        tf_FoneCom = new javax.swing.JTextField();
        jL_email = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        jL_dataCadastro = new javax.swing.JLabel();
        tf_dataCadastro = new javax.swing.JTextField();
        jL_observacao = new javax.swing.JLabel();
        tf_observacao = new javax.swing.JTextField();
        jL_foto = new javax.swing.JLabel();
        tf_foto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        botao_impressao = new javax.swing.JButton();
        botao_impressao1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO DE CIDADES");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel4.setText("Nome.:");

        jL_codigo.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jL_codigo.setText("Codigo.:");

        cb_endereco.setToolTipText("selecione a unidade federativa(estado)");

        tf_codigo.setToolTipText("digite  o codigo da cidade");
        tf_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoActionPerformed(evt);
            }
        });

        tf_nome.setToolTipText("digite o nome da cidade");
        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });

        botao_primeiro_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/primeiro.jpg"))); // NOI18N
        botao_primeiro_registro.setToolTipText("volta para o primeiro registro");
        botao_primeiro_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_primeiro_registroActionPerformed(evt);
            }
        });

        botao_registro_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/tras.jpg"))); // NOI18N
        botao_registro_anterior.setToolTipText("volta um registro");
        botao_registro_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_registro_anteriorActionPerformed(evt);
            }
        });

        botao_registro_frente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/frente.jpg"))); // NOI18N
        botao_registro_frente.setToolTipText("vai para o proximo registro");
        botao_registro_frente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_registro_frenteActionPerformed(evt);
            }
        });

        botao_ultimo_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/ultimo.jpg"))); // NOI18N
        botao_ultimo_registro.setToolTipText("vai para o ultimo registro");
        botao_ultimo_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ultimo_registroActionPerformed(evt);
            }
        });

        botao_gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/gravar1.jpg"))); // NOI18N
        botao_gravar.setToolTipText("grava o registro");
        botao_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_gravarActionPerformed(evt);
            }
        });

        botao_incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/novo.jpg"))); // NOI18N
        botao_incluir.setToolTipText("inclui um registro");
        botao_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_incluirActionPerformed(evt);
            }
        });

        botao_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/excluir2.jpg"))); // NOI18N
        botao_excluir.setToolTipText("exclui um registro");
        botao_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirActionPerformed(evt);
            }
        });

        botao_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/alterar2.jpg"))); // NOI18N
        botao_alterar.setToolTipText("altera um registro");
        botao_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        tf_pesquisa.setToolTipText("digite o nome da cidade para pesquisar");
        tf_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pesquisaActionPerformed(evt);
            }
        });

        jcb_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_pesquisarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/pesquisa.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcb_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jtb_cliente.setAutoCreateRowSorter(true);
        jtb_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Fone Res.", "Fone Com.", "Fone Cel.", "E-mail"
            }
        ));
        jtb_cliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jtb_cliente.setCellSelectionEnabled(true);
        jtb_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtb_cliente.setDropMode(javax.swing.DropMode.INSERT);
        jtb_cliente.setGridColor(new java.awt.Color(0, 0, 0));
        jtb_cliente.setName(""); // NOI18N
        jScrollPane2.setViewportView(jtb_cliente);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Ordenacao");

        grupoOrdenacao.add(radioButtonCodigo);
        radioButtonCodigo.setText("Codigo");
        radioButtonCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCodigoActionPerformed(evt);
            }
        });

        grupoOrdenacao.add(radioButtonNome);
        radioButtonNome.setSelected(true);
        radioButtonNome.setText("Nome");
        radioButtonNome.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioButtonCodigo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioButtonNome)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonNome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jl_titulo_cliente.setBackground(new java.awt.Color(0, 51, 255));
        jl_titulo_cliente.setFont(new java.awt.Font("Tahoma", 1, 36));
        jl_titulo_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jl_titulo_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo_cliente.setText("CADASTRO DE CLIENTES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_titulo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_titulo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jl_endereco.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jl_endereco.setText(" Endereco.:");

        tf_CodLog.setToolTipText("digite o nome da cidade");
        tf_CodLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_CodLogActionPerformed(evt);
            }
        });

        tf_numero.setToolTipText("digite o nome da cidade");
        tf_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_numeroActionPerformed(evt);
            }
        });

        jl_numero.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jl_numero.setText("Nr.:");

        jl_complemento.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jl_complemento.setText("Complemento.:");

        tf_complemento.setToolTipText("digite o nome da cidade");
        tf_complemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_complementoActionPerformed(evt);
            }
        });

        jl_bairro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_bairro.setText("Bairro.:");

        tf_bairro.setToolTipText("digite o nome da cidade");
        tf_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bairroActionPerformed(evt);
            }
        });

        cb_bairro.setToolTipText("selecione a unidade federativa(estado)");

        jl_cidade.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jl_cidade.setText("Cidade.:");

        tf_cidade.setToolTipText("digite o nome da cidade");
        tf_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cidadeActionPerformed(evt);
            }
        });

        cb_cidade.setToolTipText("selecione a unidade federativa(estado)");

        jl_cpf.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jl_cpf.setText("CPF.:");

        tf_cpf.setToolTipText("digite o nome da cidade");
        tf_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cpfActionPerformed(evt);
            }
        });

        jl_cep.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jl_cep.setText("CEP.:");

        tf_cep.setToolTipText("digite o nome da cidade");
        tf_cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cepActionPerformed(evt);
            }
        });

        jl_rg.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jl_rg.setText(" RG.:");

        tf_rg.setToolTipText("digite o nome da cidade");
        tf_rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rgActionPerformed(evt);
            }
        });

        tf_FoneCel.setToolTipText("digite o nome da cidade");
        tf_FoneCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_FoneCelActionPerformed(evt);
            }
        });

        jl_FoneCel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_FoneCel.setText("Fone Cel.:");

        tf_dataNascimento.setToolTipText("digite o nome da cidade");
        tf_dataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dataNascimentoActionPerformed(evt);
            }
        });

        jl_dataNascimento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_dataNascimento.setText("Data de Nascimento.:");

        tf_foneRes.setToolTipText("digite o nome da cidade");
        tf_foneRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_foneResActionPerformed(evt);
            }
        });

        jl_foneRes.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jl_foneRes.setText(" Fone Res.:");

        jl_FoneCom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jl_FoneCom.setText("Fone Comercial.:");

        tf_FoneCom.setToolTipText("digite o nome da cidade");
        tf_FoneCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_FoneComActionPerformed(evt);
            }
        });

        jL_email.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jL_email.setText("E-mail.:");

        tf_email.setToolTipText("digite  o codigo da cidade");
        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });

        jL_dataCadastro.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jL_dataCadastro.setText("Data Cadastro.:");

        tf_dataCadastro.setToolTipText("digite o nome da cidade");
        tf_dataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dataCadastroActionPerformed(evt);
            }
        });

        jL_observacao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jL_observacao.setText("Observacao.:");

        tf_observacao.setToolTipText("digite o nome da cidade");
        tf_observacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_observacaoActionPerformed(evt);
            }
        });

        jL_foto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jL_foto.setText("Foto.:");

        tf_foto.setToolTipText("digite o nome da cidade");
        tf_foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_fotoActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botao_impressao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/impressora.jpg"))); // NOI18N
        botao_impressao.setToolTipText("exclui um registro");
        botao_impressao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_impressaoActionPerformed(evt);
            }
        });

        botao_impressao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/relatorio3.jpg"))); // NOI18N
        botao_impressao1.setToolTipText("exclui um registro");
        botao_impressao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_impressao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jl_complemento)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(tf_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(botao_primeiro_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botao_registro_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botao_registro_frente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(156, 156, 156)
                                        .addComponent(botao_ultimo_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jl_endereco)
                                    .addGap(14, 14, 14)
                                    .addComponent(tf_CodLog))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jL_codigo)
                                    .addGap(27, 27, 27)
                                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addGap(27, 27, 27)
                                    .addComponent(tf_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                    .addGap(278, 278, 278))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(cb_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jl_numero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jl_bairro)
                            .addGap(14, 14, 14)
                            .addComponent(tf_bairro, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(cb_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jl_cidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jl_cep)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jl_foneRes)
                                    .addGap(14, 14, 14)
                                    .addComponent(tf_foneRes, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jl_FoneCom)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_FoneCom, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(jl_FoneCel)
                                    .addGap(14, 14, 14)
                                    .addComponent(tf_FoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jl_rg)
                                    .addGap(14, 14, 14)
                                    .addComponent(tf_rg, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jl_cpf)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jl_dataNascimento)
                                    .addGap(14, 14, 14)
                                    .addComponent(tf_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(280, 280, 280))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jL_email)
                            .addGap(27, 27, 27)
                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jL_dataCadastro)
                            .addGap(27, 27, 27)
                            .addComponent(tf_dataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jL_observacao)
                            .addGap(27, 27, 27)
                            .addComponent(tf_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(376, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jL_foto)
                            .addGap(27, 27, 27)
                            .addComponent(tf_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1)
                            .addContainerGap(609, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botao_incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(botao_gravar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botao_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(botao_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(botao_impressao)
                            .addGap(18, 18, 18)
                            .addComponent(botao_impressao1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_codigo)
                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_endereco)
                    .addComponent(tf_CodLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_numero)
                    .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_complemento)
                    .addComponent(tf_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_bairro)
                    .addComponent(tf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_cidade)
                    .addComponent(tf_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_cep)
                    .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_rg)
                    .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_cpf)
                    .addComponent(jl_dataNascimento)
                    .addComponent(tf_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_foneRes)
                    .addComponent(tf_foneRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_FoneCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_FoneCom)
                    .addComponent(jl_FoneCel)
                    .addComponent(tf_FoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_email)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_dataCadastro)
                    .addComponent(tf_dataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_observacao)
                    .addComponent(tf_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_foto)
                    .addComponent(tf_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botao_primeiro_registro)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botao_registro_frente)
                                .addComponent(botao_registro_anterior)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botao_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botao_impressao1, 0, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botao_incluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botao_gravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botao_alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botao_impressao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botao_ultimo_registro)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void radioButtonNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonNomeActionPerformed
   ordem_visualizacao("nome");
   }//GEN-LAST:event_radioButtonNomeActionPerformed

   private void radioButtonCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCodigoActionPerformed
    ordem_visualizacao("codigo");
   }//GEN-LAST:event_radioButtonCodigoActionPerformed

    private void jcb_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_pesquisarActionPerformed
 
    if(pesquisa_combo == 1 )
    {    
        try 
     {
         
          con_cliente.resultset.first();
          String igual = "n";
          while(igual == "n")
          {
             
              
                if (con_cliente.resultset.getString("nome").equals(jcb_pesquisar.getSelectedItem()))
                {
                  igual = "s";
                }
                else 
                    con_cliente.resultset.next();
          }
           tf_codigo.setText(con_cliente.resultset.getString("codigo"));
           mostraDados();
           
          
      }
          
        catch(SQLException erro)
        {

            //JOptionPane.showMessageDialog(null,"Erro ao tentar pesquisar via combo box!"+erro);
        }
    }
    else
        pesquisa_combo = 1;
        
    }//GEN-LAST:event_jcb_pesquisarActionPerformed

    private void botao_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarActionPerformed
 try
     {
          String sql = "UPDATE cliente SET nome = '"+tf_nome.getText()+"',"+
                       "uf = '"+cb_endereco.getSelectedItem()+"' where codigo = "+tf_codigo.getText();
          con_cliente.statement.executeUpdate(sql);
          JOptionPane.showMessageDialog(null, "Altera?AO realizada com sucesso!");
     
          //atualiza tela
          con_cliente.executaSQL("Select * from cliente order by "+ordenacao);
          atualizaComboBox();
          con_cliente.resultset.first();
           mostraDados();
          ordem_visualizacao("codigo");
      }
          
        catch(SQLException erro)
        {

            JOptionPane.showMessageDialog(null,"Erro ao tenta alterar o registro!"+erro);
        }

    }//GEN-LAST:event_botao_alterarActionPerformed

    private void botao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirActionPerformed
    
        
      try
        {
          String sql = "select * from cliente where codigo = "+tf_codigo.getText();
          con_cliente.executaSQL(sql);
          con_cliente.resultset.first();
          String nome = "Deletar a cliente: "+con_cliente.resultset.getString("nome")+" ?";
          int opcao_escolhida = JOptionPane.showConfirmDialog(null,nome,"Exclusao ", JOptionPane.YES_NO_OPTION);
          if(opcao_escolhida==JOptionPane.YES_OPTION)
          {
            sql = "DELETE FROM cliente where codigo = "+tf_codigo.getText();
            int conseguiu_excluir = con_cliente.statement.executeUpdate(sql);
            if (conseguiu_excluir == 1)
            {
                JOptionPane.showMessageDialog(null,"ExclusAO realizada com sucesso");
                con_cliente.executaSQL("Select * from cliente order by "+ordenacao);
                atualizaComboBox();
                con_cliente.resultset.first();
                mostraDados();
                ordem_visualizacao("codigo");
            }
            
          }
          else 
             return;
          
      }
      
      
        catch(SQLException erro)
        {

            JOptionPane.showMessageDialog(null,"Erro ao tenta excluir o registro!"+erro);
        }

        
        
    }//GEN-LAST:event_botao_excluirActionPerformed
    
    private void botao_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_gravarActionPerformed
    
      try
        {
          
             String sqlinsert = "insert into cliente (nome, logradouro, numero, complemento, bairro, cidade, cep, rg, cpf, FoneRes, FoneCom, FoneCel, Email,DataNascimento, DataCadastro, foto, observacao) values ('"+tf_nome.getText()+"', '"+tf_CodLog.getText()+"', '"+tf_numero.getText()+"', '"+tf_complemento.getText()+"','"+tf_bairro.getText()+"', '"+tf_cidade.getText()+"', '"+tf_cep.getText()+"', '"+tf_rg.getText()+"', '"+tf_cpf.getText()+"', '"+tf_foneRes.getText()+"', '"+tf_FoneCom.getText()+"', '"+tf_FoneCel.getText()+"', '"+tf_email.getText()+"', '"+tf_dataNascimento.getText()+"', '"+tf_dataCadastro.getText()+"', '"+tf_foto.getText()+"', '"+tf_observacao.getText()+"')";
             con_cliente.statement.executeUpdate(sqlinsert);
             JOptionPane.showMessageDialog(null,"GRAVACAO REALIZADA COM SUCESSO!");
             con_cliente.executaSQL("select * from cliente");
             //atualizaComboBox();
             con_cliente.resultset.last();
             mostraDados();
             ordem_visualizacao("codigo");
        }
        catch(SQLException erro)
        {

            JOptionPane.showMessageDialog(null,"ERRO AO GRAVAR OS DADOS"+erro);
        }
                  
    }//GEN-LAST:event_botao_gravarActionPerformed

    private void botao_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_incluirActionPerformed

            tf_codigo.setText("");
            tf_nome.setText("");
            tf_CodLog.setText("");
            tf_numero.setText("");
            tf_complemento.setText("");
            tf_bairro.setText("");
            tf_cidade.setText("");
            tf_cpf.setText("");
            tf_rg.setText("");
            tf_cep.setText("");
            tf_foneRes.setText("");
            tf_FoneCom.setText("");
            tf_FoneCel.setText("");
            tf_email.setText("");
            tf_dataNascimento.setText("");
            tf_foto.setText("");
            tf_observacao.setText("");
            tf_dataCadastro.setText("");
      tf_nome.requestFocus();
      tf_codigo.setEditable(false);
    }//GEN-LAST:event_botao_incluirActionPerformed

    private void botao_ultimo_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ultimo_registroActionPerformed
    try
        {
          con_cliente.resultset.last();
          mostraDados();
        }
        catch(SQLException erro)
        {

            JOptionPane.showMessageDialog(null,"dados ja se encontram no ultimo registro"+erro);
        }
    }//GEN-LAST:event_botao_ultimo_registroActionPerformed

    private void botao_registro_frenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_registro_frenteActionPerformed
    try
        {
          con_cliente.resultset.next();
          mostraDados();
          navega = 1;
        }
        catch(SQLException erro)
        {

            JOptionPane.showMessageDialog(null,"registro nao encontrado"+erro);
        }
    
    }//GEN-LAST:event_botao_registro_frenteActionPerformed

    private void botao_registro_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_registro_anteriorActionPerformed
     try
        {
          con_cliente.resultset.previous();
          mostraDados();
           navega = 0;
        }
        catch(SQLException erro)
        {

            JOptionPane.showMessageDialog(null,"registro nao encontrado"+erro);
        }
    }//GEN-LAST:event_botao_registro_anteriorActionPerformed

    private void botao_primeiro_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_primeiro_registroActionPerformed
    
     try
        {
          con_cliente.resultset.first();
          mostraDados();
          
        }
        catch(SQLException erro)
        {

            JOptionPane.showMessageDialog(null,"dados ja se encontram no primeiro registro"+erro);
        }
     
    }//GEN-LAST:event_botao_primeiro_registroActionPerformed

    private void tf_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_codigoActionPerformed

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_nomeActionPerformed

    private void tf_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pesquisaActionPerformed
             try
     {
         
          con_cliente.resultset.first();
          String igual = "n";
          int tamanho_pesquisa = tf_pesquisa.getText().length();
          while(igual == "n")
          {
              String pesquisado = con_cliente.resultset.getString("nome").substring(0, (tamanho_pesquisa));
              
                if (pesquisado.equals(tf_pesquisa.getText()))
                {
                  igual = "s";
                }
                else 
                    con_cliente.resultset.next();
          }
           tf_codigo.setText(con_cliente.resultset.getString("codigo"));
           mostraDados();
          jcb_pesquisar.setSelectedItem(tf_nome.getText());
          con_cliente.executaSQL("select * from cliente where nome like '"+tf_pesquisa.getText()+"%' order by "+ordenacao);
          preencher_jtable(); 
      }
          
        catch(SQLException erro)
        {

            JOptionPane.showMessageDialog(null,"Erro ao tentar pesquisar via digita?AO!"+erro);
        }
    }//GEN-LAST:event_tf_pesquisaActionPerformed

    private void tf_CodLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_CodLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_CodLogActionPerformed

    private void tf_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_numeroActionPerformed

    private void tf_complementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_complementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_complementoActionPerformed

    private void tf_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bairroActionPerformed

    private void tf_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cidadeActionPerformed

    private void tf_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cpfActionPerformed

    private void tf_cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cepActionPerformed

    private void tf_rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_rgActionPerformed

    private void tf_FoneCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_FoneCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_FoneCelActionPerformed

    private void tf_dataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dataNascimentoActionPerformed

    private void tf_foneResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_foneResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_foneResActionPerformed

    private void tf_FoneComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_FoneComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_FoneComActionPerformed

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    private void tf_dataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dataCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dataCadastroActionPerformed

    private void tf_observacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_observacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_observacaoActionPerformed

    private void tf_fotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_fotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fotoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botao_impressaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_impressaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_impressaoActionPerformed

    private void botao_impressao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_impressao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_impressao1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_alterar;
    private javax.swing.JButton botao_excluir;
    private javax.swing.JButton botao_gravar;
    private javax.swing.JButton botao_impressao;
    private javax.swing.JButton botao_impressao1;
    private javax.swing.JButton botao_incluir;
    private javax.swing.JButton botao_primeiro_registro;
    private javax.swing.JButton botao_registro_anterior;
    private javax.swing.JButton botao_registro_frente;
    private javax.swing.JButton botao_ultimo_registro;
    private javax.swing.JComboBox cb_bairro;
    private javax.swing.JComboBox cb_cidade;
    private javax.swing.JComboBox cb_endereco;
    private javax.swing.ButtonGroup grupoOrdenacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jL_codigo;
    private javax.swing.JLabel jL_dataCadastro;
    private javax.swing.JLabel jL_email;
    private javax.swing.JLabel jL_foto;
    private javax.swing.JLabel jL_observacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcb_pesquisar;
    private javax.swing.JLabel jl_FoneCel;
    private javax.swing.JLabel jl_FoneCom;
    private javax.swing.JLabel jl_bairro;
    private javax.swing.JLabel jl_cep;
    private javax.swing.JLabel jl_cidade;
    private javax.swing.JLabel jl_complemento;
    private javax.swing.JLabel jl_cpf;
    private javax.swing.JLabel jl_dataNascimento;
    private javax.swing.JLabel jl_endereco;
    private javax.swing.JLabel jl_foneRes;
    private javax.swing.JLabel jl_numero;
    private javax.swing.JLabel jl_rg;
    private javax.swing.JLabel jl_titulo_cliente;
    private javax.swing.JTable jtb_cliente;
    private javax.swing.JRadioButton radioButtonCodigo;
    private javax.swing.JRadioButton radioButtonNome;
    private javax.swing.JTextField tf_CodLog;
    private javax.swing.JTextField tf_FoneCel;
    private javax.swing.JTextField tf_FoneCom;
    private javax.swing.JTextField tf_bairro;
    private javax.swing.JTextField tf_cep;
    private javax.swing.JTextField tf_cidade;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_complemento;
    private javax.swing.JTextField tf_cpf;
    private javax.swing.JTextField tf_dataCadastro;
    private javax.swing.JTextField tf_dataNascimento;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_foneRes;
    private javax.swing.JTextField tf_foto;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_numero;
    private javax.swing.JTextField tf_observacao;
    private javax.swing.JTextField tf_pesquisa;
    private javax.swing.JTextField tf_rg;
    // End of variables declaration//GEN-END:variables

    
    public void mostraDados()
    {
        try
        {
            tf_codigo.setText(con_cliente.resultset.getString("codigo"));
            tf_nome.setText(con_cliente.resultset.getString("nome"));
            tf_CodLog.setText(con_cliente.resultset.getString("logradouro"));
            tf_numero.setText(con_cliente.resultset.getString("numero"));
            tf_complemento.setText(con_cliente.resultset.getString("complemento"));
            tf_bairro.setText(con_cliente.resultset.getString("bairro"));
            tf_cidade.setText(con_cliente.resultset.getString("cidade"));
            tf_cpf.setText(con_cliente.resultset.getString("cpf"));
            tf_rg.setText(con_cliente.resultset.getString("rg"));
            tf_cep.setText(con_cliente.resultset.getString("cep"));
            tf_foneRes.setText(con_cliente.resultset.getString("FoneRes"));
            tf_FoneCom.setText(con_cliente.resultset.getString("FoneCom"));
            tf_FoneCel.setText(con_cliente.resultset.getString("FoneCel"));
            tf_email.setText(con_cliente.resultset.getString("Email"));
            tf_dataNascimento.setText(con_cliente.resultset.getString("DataNascimento"));
            tf_dataCadastro.setText(con_cliente.resultset.getString("DataCadastro"));
            tf_foto.setText(con_cliente.resultset.getString("foto"));
            tf_observacao.setText(con_cliente.resultset.getString("observacao"));


           // cb_endereco.setSelectedItem(con_cliente.resultset.getString("uf"));
        }
        catch(SQLException erro)
        {
            if(navega==1)
            JOptionPane.showMessageDialog(null,"voce ja esta nu ultimo registro");
               else 
                  if(navega==0)
                  JOptionPane.showMessageDialog(null,"voce ja esta nu primeiro registro");
                   else
                   JOptionPane.showMessageDialog(null,"dados nAO localizados"+erro);
        }
        
        
    }
    
    public void atualizaComboBox(){
    
      try
     {
        jcb_pesquisar.removeAllItems();
        con_cliente.executaSQL("Select * from cliente order by "+ordenacao);
         while (con_cliente.resultset.next())
             jcb_pesquisar.addItem(con_cliente.resultset.getString("nome"));
         
          
      }
          
        catch(SQLException erro)
        {

            JOptionPane.showMessageDialog(null,"Erro ao atualizar o combobox de pesquisa!"+erro);
        }

        
    
    }
    
    public void preencher_jtable()
    {
        jtb_cliente.getColumnModel().getColumn(0).setPreferredWidth(20);
        jtb_cliente.getColumnModel().getColumn(1).setPreferredWidth(150);
        jtb_cliente.getColumnModel().getColumn(2).setPreferredWidth(20);
        
        DefaultTableModel modelo = (DefaultTableModel)jtb_cliente.getModel();
        modelo.setNumRows(0);
        
        try
        {
            while (con_cliente.resultset.next())
                modelo.addRow(new Object[]{con_cliente.resultset.getString("codigo"), con_cliente.resultset.getString("nome"), con_cliente.resultset.getString("uf")});
                con_cliente.resultset.first();
        }
        
        catch(SQLException erro)
        {

            JOptionPane.showMessageDialog(null,"Erro ao listar no jtable!"+erro);
        }
    }
    
    public void ordem_visualizacao(String ordem)
    {
        ordenacao = ordem;
        con_cliente.executaSQL("select * from cliente order by "+ordenacao);
        preencher_jtable();
        //atualizaComboBox();
        
        try 
        {
            con_cliente.resultset.first();
        }
        catch (SQLException erro) { 
            JOptionPane.showMessageDialog(null,"Erro na ordena?AO dos dados"+erro);
        }
        
        mostraDados();
    }
}
    
